version: '3.8'

services:
  db:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: docker_workshop
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
  mail:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'
  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  postgres_data:
  minio_data:
